include:
  - project: devops/default-pipelines
    ref: master
    file: 'go.yaml'

stages:
  - validate
  - build
  - release

test:
  extends: .go-test-postgis
  variables:
    GO_TEST_COVERAGE_FILE_EXCLUDE_PATTERN: mock.go

lint:
  extends: .go-lint
  variables:
    GOLANGCI_EXIT_CODE: "1"

godoc:
  extends: .go-doc-pages